"""
SentinelAI — Professional Report Exporter
Converts Markdown audit reports to styled HTML and PDF.
"""

import os
import re
import markdown2
from datetime import datetime
from pathlib import Path

# Try to import weasyprint; if it fails (missing system deps), we still have HTML export
try:
    from weasyprint import HTML as WeasyHTML
    HAS_WEASYPRINT = True
except (ImportError, OSError):
    HAS_WEASYPRINT = False


TEMPLATES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")


def _load_css() -> str:
    """Load the corporate report stylesheet."""
    css_path = os.path.join(TEMPLATES_DIR, "report_style.css")
    try:
        with open(css_path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "body { font-family: sans-serif; background: #0f172a; color: #f1f5f9; }"


def _strip_rich_markup(text: str) -> str:
    """Remove Textual/Rich markup tags like [bold green]...[/bold green] from text."""
    # Remove [tag]...[/tag] style markup
    text = re.sub(r'\[/?[a-z_ ]+\]', '', text, flags=re.IGNORECASE)
    # Remove lines that are purely separator characters
    text = re.sub(r'^[=]{10,}$', '---', text, flags=re.MULTILINE)
    # Remove [dim]...[/dim] style status lines
    text = re.sub(r'\[dim\].*?\[/dim\]', '', text, flags=re.DOTALL)
    return text.strip()


def _extract_phases_for_toc(html_content: str) -> list:
    """Extract phase headings from the HTML to build a table of contents."""
    pattern = r'<h2[^>]*>(.*?)</h2>'
    headings = re.findall(pattern, html_content, re.IGNORECASE)
    # Clean HTML tags from headings
    clean_headings = []
    for h in headings:
        clean = re.sub(r'<[^>]+>', '', h).strip()
        if clean:
            clean_headings.append(clean)
    return clean_headings


def _colorize_severity(html: str) -> str:
    """Post-process HTML to add severity badge classes to table cells."""
    severity_map = {
        'Critical': 'severity-critical',
        'High': 'severity-high',
        'Medium': 'severity-medium',
        'Low': 'severity-low',
    }
    for severity, css_class in severity_map.items():
        # Match <strong>Critical</strong> etc in table cells
        html = html.replace(
            f'<strong>{severity}</strong>',
            f'<strong class="{css_class}">{severity}</strong>'
        )
    return html


def _build_html_report(report_md: str, suggestions_md: str, target: str) -> str:
    """Build a full self-contained HTML document from the audit report."""
    
    css = _load_css()
    
    # Clean Rich markup from the markdown
    clean_report = _strip_rich_markup(report_md)
    clean_suggestions = _strip_rich_markup(suggestions_md)
    
    # Convert Markdown to HTML
    report_html = markdown2.markdown(
        clean_report,
        extras=["tables", "fenced-code-blocks", "code-friendly", "break-on-newline"]
    )
    
    suggestions_html = markdown2.markdown(
        clean_suggestions,
        extras=["tables", "fenced-code-blocks", "code-friendly", "break-on-newline"]
    )
    
    # Post-process: add severity colors
    report_html = _colorize_severity(report_html)
    
    # Build Table of Contents
    headings = _extract_phases_for_toc(report_html)
    toc_items = ""
    for i, heading in enumerate(headings):
        anchor = re.sub(r'[^a-z0-9]+', '-', heading.lower()).strip('-')
        toc_items += f'<li><a href="#{anchor}">{heading}</a></li>\n'
        # Inject anchors into the report HTML
        report_html = report_html.replace(
            f'<h2>{heading}</h2>',
            f'<h2 id="{anchor}">{heading}</h2>',
            1
        )
    
    # Metadata
    now = datetime.now()
    timestamp = now.strftime("%B %d, %Y at %I:%M %p")
    date_iso = now.strftime("%Y-%m-%d")
    
    # Assemble full HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SentinelAI Security Audit Report — {target}</title>
    <meta name="description" content="AI-powered security audit report generated by SentinelAI for {target}">
    <meta name="generator" content="SentinelAI Enterprise Security Auditor">
    <style>
{css}
    </style>
</head>
<body>

    <!-- REPORT HEADER -->
    <div class="report-header">
        <div class="logo-area">
            <div class="logo-icon">S</div>
            <div class="logo-text">Sentinel<span>AI</span></div>
        </div>
        <div style="color: var(--text-muted); font-size: 13px; margin-bottom: 8px;">
            Enterprise Security Audit Report
        </div>
        <div class="meta-grid">
            <div class="meta-item">
                <div class="meta-label">Target</div>
                <div class="meta-value">{target}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Generated</div>
                <div class="meta-value">{timestamp}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Report ID</div>
                <div class="meta-value">SAI-{date_iso}-{abs(hash(target)) % 10000:04d}</div>
            </div>
        </div>
    </div>

    <!-- TABLE OF CONTENTS -->
    <div class="toc">
        <h2>Table of Contents</h2>
        <ol>
{toc_items}
        </ol>
    </div>

    <!-- REPORT BODY -->
    <div class="report-body">
{report_html}
    </div>

    <!-- SUGGESTIONS -->
    <div class="report-body">
        <div class="suggestions-section">
            <h2 id="remediation-suggestions">Prioritized Remediation Suggestions</h2>
{suggestions_html}
        </div>
    </div>

    <!-- FOOTER -->
    <div class="report-footer">
        <div class="disclaimer">
            This report was generated by <strong>SentinelAI</strong> — an AI-powered security auditing tool.
            Findings are based on automated analysis and should be verified by a qualified security professional
            before taking action. This report is confidential and intended for authorized recipients only.
        </div>
        <div style="margin-top: 12px; color: var(--text-muted);">
            &copy; {now.year} SentinelAI &mdash; AI-Powered Security Auditing
        </div>
    </div>

</body>
</html>"""
    
    return html


def export_to_html(report_md: str, suggestions_md: str, target: str, output_path: str = None) -> str:
    """
    Export the audit report as a self-contained HTML file.
    
    Returns the absolute path to the generated file.
    """
    html = _build_html_report(report_md, suggestions_md, target)
    
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = f"sentinel_report_{timestamp}.html"
    
    output_path = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    
    return output_path


def export_to_pdf(report_md: str, suggestions_md: str, target: str, output_path: str = None) -> str:
    """
    Export the audit report as a PDF file.
    Falls back to HTML export if weasyprint is not available.
    
    Returns the absolute path to the generated file.
    """
    if not HAS_WEASYPRINT:
        # Fallback: export as HTML and inform the user
        html_path = export_to_html(report_md, suggestions_md, target)
        raise RuntimeError(
            f"WeasyPrint is not available (missing system deps). "
            f"Exported as HTML instead: {html_path}\n"
            f"You can open this in a browser and Print → Save as PDF."
        )
    
    html_content = _build_html_report(report_md, suggestions_md, target)
    
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = f"sentinel_report_{timestamp}.pdf"
    
    output_path = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    
    weasy_doc = WeasyHTML(string=html_content)
    weasy_doc.write_pdf(output_path)
    
    return output_path


def get_export_capabilities() -> dict:
    """Check which export formats are available."""
    return {
        "html": True,
        "pdf": HAS_WEASYPRINT,
    }
